<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileIt.Module.HolderHoldingsFlow.App\FileIt.Module.HolderHoldingsFlow.App.csproj" />
    <ProjectReference Include="..\FileIt.Module.HolderHoldingsFlow.Integration\FileIt.Module.HolderHoldingsFlow.Integration.csproj" />
    <ProjectReference Include="..\FileIt.Module.HolderHoldingsFlow.Domain\FileIt.Module.HolderHoldingsFlow.Domain.csproj" />
  </ItemGroup>

</Project>